### ISSUE TITLE
Spritesheets exporting with white background

### ISSUE THREAD

**Issue by etoby50** [Falano/kritaSpritesheetManager#22] opened 2023-06-29 11:34 UTC
Spritesheets are exporting with a white background. Krita exports the regular PNG file of a single frame as transparent, but the full spritesheet ends up with a background. Possibly an issue with spritesheetexporter.py line 339?

Screenshot shows the issue as best I can. I changed nothing about the krita document in between these two exports.

<img width="545" alt="Screen Shot 2023-06-29 at 12 33 16 PM" src="https://github.com/Falano/kritaSpritesheetManager/assets/113868759/3eccf013-60aa-4c4e-a4ed-d8e3580382f5">

**Comment by Falano** [comment] 2023-06-29 19:22
I'll have a look at how to fix it in the script.
In the meantime, there should be an easy manual fix: I think the issue is with the default New Document options: if you create a new document, go to the Content tab, and change the background opacity to 0 (and then close the new image if you don't need it), it should remember the settings and not add a white layer on every new document.
(if it does not work let me know!)

**Comment by etoby50** [comment] 2023-07-10 18:10
Still not working. I'm baffled, please let me know if you find something.

**Comment by Falano** [comment] 2023-07-11 12:42
Uh, that's weird, it works on my end.
Which version of krita are you using?
Could you please send me a screenshot of the options of the Spritesheet Exporter (with "use Custom export Settings" toggled on)?
And if you untoggle "Remove individual sprites", it should make a subfolder in the directory your .kra file is in, which contains the exported individual spritesheets. Do they have a transparent or white background?

**Comment by etoby50** [comment] 2023-07-12 16:58
I'm using Krita 5.1.5. I turned off remove individual sprites, and they are transparent, but the full spritesheet isn't. Your screenshot is included.

<img width="505" alt="Screen Shot 2023-07-12 at 9 52 29 AM" src="https://github.com/Falano/kritaSpritesheetManager/assets/113868759/e9500d42-c5d3-4dba-b539-824387699146">

**Comment by Falano** [comment] 2023-07-20 11:11
I tried a couple things, but I did not manage to replicate it, so I have no clue where it could be coming from.
I'd say try with another file just in case, check that in your png export settings you do have Store alpha channel toggled on, and try once to export with just the default settings / names, but other than that I'm stumped.

A dirty fix of sorts would be to, in your png export settings, _uncheck_ Store alpha channel, and set the transparent color as one you don't use (pure RGB magenta for example), and then use the Color to Alpha filter before saving over as png (with alpha channel stored this time); which is a bit cumbersome, but the best I have.

(it would be interesting to set the png alpha color to one non-white color, say, magenta, the default background layer in a new image to another non-white color, say, green, have a number of frames where a few sprites are left empty (7? 13?), and see what it exports like)

**Comment by pewsplosions** [comment] 2023-08-09 23:33
I'm having this issue as well. Not sure if this helps but I was not experiencing this on my Linux machine with Kubuntu. Only on my Windows 10 computer. No changes in kra file between the two, just works as expected on Linux, white background on Windows.

**Comment by DoodleSurf** [comment] 2023-10-28 14:16
This is a 5.1.5 issue, updating krita to 5.2 fixed the problem for me.

**Comment by Falano** [comment] 2023-10-30 18:11
thanks a lot!
I'm closing the issue then.

**Closed as completed** 2023-10-30 18:12 UTC
